version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: soe_postgres
    restart: always
    environment:
      POSTGRES_DB: soe_asset_db
      POSTGRES_USER: soe_admin
      POSTGRES_PASSWORD: soe_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: